export const SET_DOUGH = "SET_DOUGH";
export const SET_SOUCE = "SET_SOUCE";
export const SET_SIZE = "SET_SIZE";
export const SET_INGREDIENT_COUNT = "SET_INGREDIENT_COUNT";
export const SET_CLASS_TO_ELEMS = "SET_CLASS_TO_ELEMS";
export const SET_NAME = "SET_NAME";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CLEAR_PIZZA_CONFIGURATION= "CLEAR_PIZZA_CONFIGURATION";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const CHANGE_PIZZA_CONFIGURATION = "CHANGE_PIZZA_CONFIGURATION";
export const HANDLE_ORDER = "HANDLE_ORDER";
export const ADD_ORDER_INFO = "ADD_ORDER_INFO";

