export const SET_DOUGH = "SET_DOUGH";
export const SET_SOUCE = "SET_SOUCE";
export const SET_SIZE = "SET_SIZE";
export const SET_INGREDIENT_COUNT = "SET_INGREDIENT_COUNT";
export const SET_CLASS_TO_ELEMS = "SET_CLASS_TO_ELEMS";
export const SET_NAME = "SET_NAME";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const CLEAR_PIZZA_CONFIGURATION= "CLEAR_PIZZA_CONFIGURATION";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";
export const CHANGE_PIZZA_CONFIGURATION = "CHANGE_PIZZA_CONFIGURATION";
export const HANDLE_ORDER = "HANDLE_ORDER";
export const CHANGE_ADDRESS_INFO = "CHANGE_ADDRESS_INFO";
export const SET_DEFAULT_QUANTITY_TO_PRODUCTS = "SET_DEFAULT_QUANTITY_TO_PRODUCTS";
export const SET_ENTITY = "SET_ENTITY";
export const SET_ORDERS = "SET_ORDERS";
export const REPEAT_ORDER = "REPEAT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const ADD_NEW_ADDRESS = "ADD_NEW_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const GET_ADDRESSES = "GET_ADDRESSES";



